<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Author_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get author by id
     */
    function get_author($id)
    {
        return $this->db->get_where('authors',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all authors
     */
    function get_all_authors()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('authors')->result_array();
    }
        
    /*
     * function to add new author
     */
    function add_author($params)
    {
        $this->db->insert('authors',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update author
     */
    function update_author($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('authors',$params);
    }
    
    /*
     * function to delete author
     */
    function delete_author($id)
    {
        return $this->db->delete('authors',array('id'=>$id));
    }
}
